---
apiVersion: v1
kind: Namespace
metadata:
  name: collector

---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: k8s-monitoring
  namespace: collector
spec:
  interval: 5m
  url: https://grafana.github.io/helm-charts

---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: k8s-monitoring
  namespace: collector
spec:
  interval: 5m
  chart:
    spec:
      chart: k8s-monitoring
      version: '2.0.6'
      sourceRef:
        kind: HelmRepository
        name: k8s-monitoring
      interval: 5m

  # https://fluxcd.io/flux/components/helm/helmreleases/#values-references
  # note that we can use both valuesFrom, and values:
  valuesFrom:
    - kind: ConfigMap
      name: k8s-int-otlp-destinations
      valuesKey: destinations-list

  values:
    cluster:
      name: stadler-k8s-int
    alloy-receiver:
      enabled: true
      controller:
        type: deployment
      alloy:
        extraPorts:
          - name: otlp-http
            port: 4318
            targetPort: 4318
            protocol: TCP
          - name: otlp-grpc
            port: 4317
            targetPort: 4317
            protocol: TCP
    applicationObservability:
      enabled: true
      receivers:
        otlp:
          grpc:
            enabled: true
          http:
            enabled: true
    clusterEvents:
      enabled: true
    clusterMetrics:
      enabled: true
    alloy-metrics:
      enabled: true
    alloy-singleton:
      enabled: true
