---
apiVersion: v1
kind: Namespace
metadata:
  name: collector

---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: k8s-monitoring
  namespace: collector
spec:
  interval: 5m
  url: https://grafana.github.io/helm-charts

---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: k8s-monitoring
  namespace: collector
spec:
  interval: 5m
  chart:
    spec:
      chart: k8s-monitoring
      version: '2.0.6'
      sourceRef:
        kind: HelmRepository
        name: k8s-monitoring
      interval: 5m
  values:
    cluster:
      name: stadler-k8s-int

    destinations:
      - name: otlp-gateway
        type: otlp
        url: https://YOUR_OTLP_GATEWAY.grafana.net/otlp
        protocol: http

        auth:
          type: basic
          usernameKey: username
          passwordKey: password
        secret:
          create: false
          name: grafanacloud-otlphttp-secret
          namespace: collector

        metrics: {enabled: true}
        logs: {enabled: true}
        traces: {enabled: true}

    alloy-receiver:
      enabled: true
      controller:
        type: deployment
      alloy:
        extraPorts:
          - name: otlp-http
            port: 4318
            targetPort: 4318
            protocol: TCP
          - name: otlp-grpc
            port: 4317
            targetPort: 4317
            protocol: TCP

    applicationObservability:
      enabled: true
      receivers:
        otlp:
          grpc:
            enabled: true
          http:
            enabled: true

    clusterEvents:
      enabled: true

    clusterMetrics:
      enabled: true

    alloy-metrics:
      enabled: true

    alloy-singleton:
      enabled: true
