### for now, production is identical to staging
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: open-telemetry
  namespace: open-telemetry
spec:
  values:

    # point the services to Alloy as their OTel Collector
    default:
      envOverrides:
        - name: OTEL_COLLECTOR_NAME
          value: alloy.collector

    # turn off the included olly stack
    opentelemetry-collector:
      enabled: false

    jaeger:
      enabled: false

    prometheus:
      enabled: false

    grafana:
      enabled: false

    opensearch:
      enabled: false

    # components:

    #   # set up LB ingress for the proxy (i.e. for k6 testing)
    #   frontendProxy:
    #     service:
    #       type: LoadBalancer